### ISSUE TITLE
Disabling a kind of alarm

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/alarms#13]
Currently AlarmConfiguration::SeverityConfigurationType::severityLevelList allows to configure the severity of an alarm, but it is not possible to configure that the alarm shall neither be listed in the CurrentAlarmList nor be indicated by notification.

Potential Proposal:
The SeverityType enumeration shall be complemented by an additional DISABLED value.

Or is this not to be mixed with the severity configuration?

**Comment by DanielaSpreafico** [comment]
In general when an alarm should not be present/listed on CurrentAlarmList then also on AlarmConfiguration::SeverityConfiguration should not be present/listed. 

Is the requirement  to have a configuration by the client to disable an alarm that the node listed as allowed on AlarmConfiguration::SeverityConfiguration ?

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 6th of September 2023:**
This issue will be implicitly decided together with [a proposal in issue #12](https://github.com/openBackhaul/alarms/issues/12#issuecomment-1661888188).

**Comment by openBackhaul** [comment]
This issue has been implicitly decided together with [issue #12](https://github.com/openBackhaul/alarms/issues/12#issuecomment-1661888188).
