### ISSUE TITLE
Just two types of notifications?

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/alarms#5]
Usual technology specific models are offering four types of notifications:
- ObjectCreationNotification
- ObjectDeletionNotification
- AttributeValueChangedNotification
- ProblemNotification

Because not object gets instantiated or deleted in the Alarms modelling there would be just two types of notifications, right?
- AttributeValueChangedNotification
- AlarmEventNotification

**Comment by michbin** [comment]
I would not expect to find Attribute Value Change Notifications in the information model for alarms (expect those related to alarm configuration, of course).
