### ISSUE TITLE
Values for "probable-cause" not clear

### ISSUE THREAD

**Issue by michbin** [openBackhaul/alarms#8]
The `probable-cause` attribute in the `alarm-inventory-list` is of type `int16`. It is not clear which values should or may be reported in this attribute.

The comment refers to X.733 but I could not find numerical values there. Furthermore, devices may report additional probable causes, e.g. from X.736 or M.3100.

**Comment by openBackhaul** [comment]
Vendors to please prepare for agreeing a common reference.

**Comment by eduardoyusta** [comment]
As a potential reference to address this issue:

-X.721 (as indicated in X.733 11.2.6) includes values for the generic probable causes of X.733 table 4:
https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.721-199202-I!!PDF-E&type=items 
Values can be found in X.721 section 14.2, numbering subsequently causes from 1-57 as ordered originally in X.733 table 4 (alphabetically).

-Values for security specific alarm causes (X.736) are also included in X.721 section14.2, problem being that they are also integers and overlap with the previous ones (1-18), so this requires discussion.

-Did not find details about M.3100, will still require algnment

**Comment by demx8as6** [comment]
Integers are defined in ITU-T X.721 section 14.2
Security related AlarmCategoryTypes are defined in ITU-T X.736

- int 1-57 for alarmCategoryTypes defined in ITU-T X.733
- int 1-18 for alarmCategoryTypes defined in ITU-T X.736 Table 1

Consequence: Only the combination of AlarmCategoryType and ProbableCauseInteger is unique.

**Comment by openBackhaul** [comment]
**Decision made at the 5G-xhaul call on 2nd of March 2022:**
Comment at AlarmKindType::probableCause : Integer shall be replaced by:
"If the value of the alarm-category attribute is chosen from ITU-T X.733, values 1-57 of this attribute have to be applied according to ITU-T X.721 section 14.2. If the value of the alarm-category attribute is chosen from ITU-T X.736, values 1-18 of this attribute have to be applied according to ITU-T X.721 section 14.2. 
If probable-cause and alarm-category cannot be mapped to those defined in ITU-T X.733 and ITU-T X.736, then the default value shall be represented in this attribute. In such case, the probable-cause-string attribute might be used."
